"""초기 스키마

Revision ID: 80b3129e0173
Revises: 
Create Date: 2026-03-16 21:22:31.487183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '80b3129e0173'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkup_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('checkup_package',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hospital_name', sa.String(length=200), nullable=False),
    sa.Column('target_gender', sa.String(length=10), nullable=False),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.Column('price_range', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_checkup_package_active', 'checkup_package', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_checkup_package_target', 'checkup_package', ['target_gender', 'min_age', 'max_age'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('intake_session',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('selected_symptoms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('underlying_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('extracted_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('red_flag_level', sa.String(length=20), nullable=False),
    sa.Column('red_flag_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_provider', sa.String(length=20), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_key')
    )
    op.create_index('idx_intake_session_created', 'intake_session', ['created_at'], unique=False)
    op.create_index('idx_intake_session_gender', 'intake_session', ['gender'], unique=False)
    op.create_index('idx_intake_session_red_flag', 'intake_session', ['red_flag_level'], unique=False, postgresql_where="red_flag_level != 'NONE'")
    op.create_table('symptom_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_symptom_tag_category', 'symptom_tag', ['category'], unique=False)
    op.create_table('checkup_package_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['checkup_item.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['checkup_package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('package_symptom_tag',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('symptom_tag_id', sa.BigInteger(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 1', name='ck_relevance_score_range'),
    sa.ForeignKeyConstraint(['package_id'], ['checkup_package.id'], ),
    sa.ForeignKeyConstraint(['symptom_tag_id'], ['symptom_tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_package_symptom_tag_pkg', 'package_symptom_tag', ['package_id'], unique=False)
    op.create_index('idx_package_symptom_tag_tag', 'package_symptom_tag', ['symptom_tag_id'], unique=False)
    op.create_table('recommendation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('package_id', sa.BigInteger(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('matched_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.String(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['checkup_package.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['intake_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendation_package', 'recommendation', ['package_id'], unique=False)
    op.create_index('idx_recommendation_session', 'recommendation', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recommendation_session', table_name='recommendation')
    op.drop_index('idx_recommendation_package', table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index('idx_package_symptom_tag_tag', table_name='package_symptom_tag')
    op.drop_index('idx_package_symptom_tag_pkg', table_name='package_symptom_tag')
    op.drop_table('package_symptom_tag')
    op.drop_table('checkup_package_item')
    op.drop_index('idx_symptom_tag_category', table_name='symptom_tag')
    op.drop_table('symptom_tag')
    op.drop_index('idx_intake_session_red_flag', table_name='intake_session', postgresql_where="red_flag_level != 'NONE'")
    op.drop_index('idx_intake_session_gender', table_name='intake_session')
    op.drop_index('idx_intake_session_created', table_name='intake_session')
    op.drop_table('intake_session')
    op.drop_index('idx_checkup_package_target', table_name='checkup_package', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_checkup_package_active', table_name='checkup_package', postgresql_where=sa.text('is_active = true'))
    op.drop_table('checkup_package')
    op.drop_table('checkup_item')
    # ### end Alembic commands ###
