"""created_at/updated_at VARCHAR를 TIMESTAMP로 변경

Revision ID: a6a787d1469f
Revises: a1b2c3d4e5f6
Create Date: 2026-03-23 15:16:46.726436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a787d1469f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    tables_with_created_at = [
        'checkup_item', 'checkup_package', 'intake_session',
        'recommendation', 'symptom_tag',
    ]
    for table in tables_with_created_at:
        op.execute(
            f'ALTER TABLE {table} ALTER COLUMN created_at '
            f'TYPE TIMESTAMP USING created_at::timestamp'
        )

    op.execute(
        'ALTER TABLE checkup_package ALTER COLUMN updated_at '
        'TYPE TIMESTAMP USING updated_at::timestamp'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('symptom_tag', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('recommendation', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('intake_session', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('checkup_package', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('checkup_package', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('checkup_item', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
